class SeedProducts < ActiveRecord::Migration[5.2]
  def change
    Product.create  title: '4 cheese',
                    description: 'Не подражаемая пицца из четырех неподражаемых сыров. Для истинных вегатарианцев.',
                    size: 40,
                    price: 450,
                    is_spisy: false,
                    is_veg: true,
                    is_best_offer: false,
                    path_to_image: '/images/pizza-4-cheese.jpg'
    Product.create  title: '4 cheese little',
                    description: 'Малюсенькая. Не подражаемая пицца из четырех неподражаемых сыров. Для истинных вегатарианцев.',
                    size: 25,
                    price: 350,
                    is_spisy: false,
                    is_veg: true,
                    is_best_offer: false,
                    path_to_image: '/images/pizza-4-cheese.jpg'
    Product.create  title: '4 cheese mega',
                    description: 'Огромнющая. По лучшей цене. Не подражаемая пицца из четырех неподражаемых сыров. Для истинных вегатарианцев.',
                    size: 90,
                    price: 550,
                    is_spisy: false,
                    is_veg: true,
                    is_best_offer: true,
                    path_to_image: '/images/pizza-4-cheese.jpg'
    Product.create  title: 'bacon',
                    description: 'Не подражаемая пицца из великолепного бекона. Для истинных ценителей животинки.',
                    size: 40,
                    price: 470,
                    is_spisy: false,
                    is_veg: false,
                    is_best_offer: false,
                    path_to_image: '/images/pizza-bacon.jpg'
    Product.create  title: 'bacon little',
                    description: 'Малюсенькая. Не подражаемая пицца из великолепного бекона. Для истинных ценителей животинки.',
                    size: 25,
                    price: 370,
                    is_spisy: false,
                    is_veg: false,
                    is_best_offer: false,
                    path_to_image: '/images/pizza-bacon.jpg'
    Product.create  title: 'bacon mega',
                    description: 'Огромнющая. По лучшей цене. Не подражаемая пицца из великолепного бекона. Для истинных ценителей животинки.',
                    size: 90,
                    price: 570,
                    is_spisy: false,
                    is_veg: false,
                    is_best_offer: true,
                    path_to_image: '/images/pizza-bacon.jpg'
    Product.create  title: 'pepperoni',
                    description: 'Не подражаемая острая пицца с салями. Для истинных ценителей остренького.',
                    size: 40,
                    price: 430,
                    is_spisy: true,
                    is_veg: false,
                    is_best_offer: false,
                    path_to_image: '/images/pizza-pepperoni.jpg'
    Product.create  title: 'pepperoni little',
                    description: 'Малюсенькая. Не подражаемая острая пицца с салями. Для истинных ценителей остренького.',
                    size: 25,
                    price: 330,
                    is_spisy: true,
                    is_veg: false,
                    is_best_offer: false,
                    path_to_image: '/images/pizza-pepperoni.jpg'
    Product.create  title: 'pepperoni mega',
                    description: 'Огромнющая. По лучшей цене. Не подражаемая острая пицца с салями. Для истинных ценителей остренького.',
                    size: 90,
                    price: 530,
                    is_spisy: true,
                    is_veg: false,
                    is_best_offer: true,
                    path_to_image: '/images/pizza-pepperoni.jpg'
  end
end
